services:
  web:
    container_name: frontend-angular
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - './src:/app/src'
      - './public:/app/public'
    command: ["nginx", "-g", "daemon off;"]
